language: node_js
node_js:
- "7"

before_install:
- openssl aes-256-cbc -K $encrypted_bbcc8cf83ca8_key -iv $encrypted_bbcc8cf83ca8_iv -in _travis/note_coding.enc -out ~/.ssh/note_coding -d
- chmod 600 ~/.ssh/note_coding
- cat _travis/sshconfig >> ~/.ssh/config

cache:
  yarn: true

addons:
  ssh_known_hosts: git.coding.net

script:
  - npm run build

after_script:
  - cd docs
  - git init
  - git config user.name "Deployment Bot"
  - git config user.email "deploy@travis-ci.org"
  - git add .
  - TZ=CST
  - git commit -m "update at `date`"
  - git remote add origin git@git.coding.net:dgeibi/note.git
  - git push origin master:coding-pages -f
