language: node_js
node_js:
- "7"

before_install:
- openssl aes-256-cbc -K $encrypted_4e2dc614325b_key -iv $encrypted_4e2dc614325b_iv -in .tra.enc -out ~/.ssh/tra -d
- chmod 600 ~/.ssh/tra
- cp .sshconfig ~/.ssh/config

cache:
  yarn: true

addons:
  ssh_known_hosts: git.coding.net

script:
  - npm run build

after_script:
  - cd docs
  - git config user.name "Deployment Bot"
  - git config user.email "deploy@travis-ci.org"
  - git init
  - git add .
  - TZ=CST
  - git commit -m "update at `date`"
  - git remote add origin git@git.coding.net:dgeibi/note.git
  - git push --force origin master:coding-pages
